### ISSUE TITLE
Error in step 4 and step 6

### ISSUE THREAD

**Issue by samteezy** [markdumay/synology-pihole#1]
I receive the following error when running the script for install as sudo:

_Step 4 from 8: Generating Docker Compose file
sed: -e expression #1, char 53: unterminated `s' command_

However, it continues though to step 6:

Step 6 from 8: Creating Pi-hole container
The TIMEZONE variable is not set. Defaulting to a blank string.
Creating network "synology-pihole_macvlan" with driver "macvlan"
Creating pihole ... error

ERROR: for pihole  Cannot start service pihole: b"Bind mount failed: '/volume1/homes/sam/synology-pihole/data/dnsmasq.d' does not exists"

ERROR: for pihole  Cannot start service pihole: b"Bind mount failed: '/volume1/homes/sam/synology-pihole/data/dnsmasq.d' does not exists"
Encountered errors while bringing up the project.
ERROR: Could not create Docker network and/or container

At this point the script exits.

**Comment by markdumay** [comment]
Looking at the console output you shared, step 4 seems to have an error with the `safe_replace_in_file()` function, called by `create_docker_compose_file()`. Would you mind sharing your command-line parameters and/or `.env` file?

Seemingly there are additional issues too. The timezone is also empty - what does the following command return on your NAS?
```
find /usr/share/zoneinfo/ -type f -exec sh -c "diff -q /etc/localtime '{}' \
>             > /dev/null && echo {}" \; | sed 's|/usr/share/zoneinfo/||g'
```

And lastly, it also appears the folder `/volume1/homes/sam/synology-pihole/data/dnsmasq.d` is not created properly. The script should create `/volume1/homes/sam/synology-pihole/data/`, and Docker compose should create the subfolders `pihole` and `dnsmasq.d`. It might be Docker compose has different behavior across  versions. I'll add an issue to have the script create these two sub directories instead.

**Comment by markdumay** [comment]
I submitted a code change to the `develop` branch to tackle the missing subfolders. You can find it here:
```console
git clone https://github.com/markdumay/synology-pihole.git -b develop
```

**Comment by markdumay** [comment]
Closed due to inactivity
