### ISSUE TITLE
Update command requires IP to function

### ISSUE THREAD

**Issue by hoodncsu** [markdumay/synology-pihole#18]
- Existing instructions for scheduled update will timeout
`/bin/sh /path/to/your/script/syno_pihole.sh update -l /var/log/syno_pihole.log`

- They should specify 
`/bin/sh /path/to/your/script/syno_pihole.sh update --ip 192.168.0.250 -l /var/log/syno_pihole.log`
- Additionally, the script should exit if `--ip` is not specified.

**Comment by markdumay** [comment]
Hi @hoodncsu, thanks for your feedback. What version of the script are you using? I [fixed an issue](https://github.com/markdumay/synology-pihole/commit/2fbe5588724c8a2232a113ba00385c41a200c8fd#diff-8ad373abf531ab0983ef05c09c903c2739c9436acd9853c8c496017a3108b71b) with the update command in v1.2. Previously it did not initialize the variables correctly. It should now also warn about the missing IP address.

I'll add the `--ip` flag to the example in the README, similar to the network script. You could also use an `.env` file instead.

**Comment by hoodncsu** [comment]
My apologies, I pulled the repo a few hours before v1.2 was committed. I'll double check, but I am sure you are right. Thanks for putting this together, I ran across it in comments on http://tonylawrence.com/posts/unix/synology/free-your-synology-ports/, certainly saved me some frustration.

**Comment by hoodncsu** [comment]
Confirmed fixed in v1.2

**Comment by markdumay** [comment]
Ok, good to hear the issue has been fixed for you!
